Page destination
WildCodeSchool-2024-02/JS-Valence-P2-FinalDestination pull request #8
Opened 2024-05-16 14:34 UTC by BENSFIA

fin de css de la page destination

2024-05-19 13:24 UTC, nimser requested changes
@BENSFIA please don't push dead code.

After you make these changes, please ask a member of your team to review (approve or request change) your work.

2024-05-19 13:24 UTC, nimser commented on client/src/pages/DestinationPage.css
> +} */
Please don't commit dead code (= commented out code)

2024-05-19 13:24 UTC, nimser commented on client/src/pages/DestinationsPage.jsx
> +      </div> */}
Please don't commit dead (= commented out) code

2024-05-21 12:43 UTC, nimser requested changes

2024-05-21 12:43 UTC, nimser commented on client/src/pages/DestinationPage.css
> +*/ .title span {
CSS is broken here because `*/`

2024-05-22 08:59 UTC, Smail-al approved these changes
Good job!

2024-05-22 14:57 UTC, nimser approved these changes
ok

2024-05-22 14:57 UTC, merged